version: "3.9"

services:
  database:
    container_name: database
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U django -d django" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    mem_limit: 128m
    mem_reservation: 64M
    cpus: 0.5
    networks:
      - private

  backend:
    container_name: backend
    build: ./lib_catalog
    restart: unless-stopped
    networks:
      - private
      - public
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.5
    ports:
      - 8000:8000
    healthcheck:
      test: curl --fail http://localhost:8000/api/v1/lib/bbk/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      database:
        condition: service_healthy

  frontend:
    container_name: frontend
    build: ./frontend
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - public
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - backend
    mem_limit: 128m
    mem_reservation: 64M
    cpus: 0.5

volumes:
  data: null
networks:
  private:
    driver: bridge
  public:
    driver: bridge
